---
title: 'PH251W Group ^ Milestone #1'
output: pdf_document
date: "2025-09-26"
---
Group: 6
Ash Stivers, Alexis Gresham, Tywana Groce
Meeting Planning
What is your team's preferred communication method - email, text, bcourse messaging? 


Weekends are best. We will check in with each other for specific dates and times. We will decide together.


We will communicate throughout the google Chat throughout the week as needed. 


When will your team be holding meetings? How frequently will you meet? Are there times or days that work well for everyone?


We will meet weekly on Saturday mornings. We will use the Chat during the week and have a check in Wednesday to see where everyone is with the project. 


Discuss future non-academic commitments that might affect members' availability. 


Discuss meeting tempo: “checking in” at the beginning of meetings versus “just sticking to business”.
Roles
How is your team going to keep track of progress? Who will be taking minutes, creating agendas, and contacting the course facilitators with questions?
Tywana Groce - Organize and create agendas
Ash Stivers - Keep track of due dates and progress
Alexis Gresham - Contact course facilitators


We encourage you to discuss potential dates and times to meet with a course facilitator during Weeks 3-5. Decide on the best date and time for all.
Conflict Management
If a conflict arises, plan to solve the issue as soon as possible. This is best done using synchronous (Zoom, Google Hangouts) communication rather than asynchronous (email).


If the group is unable to resolve the conflict, seek advice from the instructional team. 
Link to repository: https://github.com/AshStivers/PH251W_Group_6.git 

Topic
Scenario 1: Infectious disease outbreak (simulated) in California
You have been given three datasets: dataset one contains weekly data about a novel infectious respiratory disease outbreak containing the number of cases and case severity by demographic categories (age category, race, sex) and geographic categories (county) for California counties (except for Los Angeles county); dataset two contains morbidity and population data by similar demographic and geographic categories for Los Angeles county, and dataset three populations estimates for 2023 by county and demographic categories. 
Description
You are an employee of the California Department of Public Health working on infectious disease surveillance.
Research question
Your supervisors are interested to know the course of the outbreak, if it is disproportionately affecting certain demographic or geographic populations and how prevention and treatment resources should be allocated.
Data

